### ISSUE TITLE
Player is alive but also not alive - Schrodinger's Terrorist Town?

### ISSUE THREAD

**Issue by djosepaci** [Tommy228/TTT_Spectator_Deathmatch#62] opened 2017-06-18 00:10 UTC
Hey! I love this addon for my server; it's beautiful, simple and effective for whoever is just bored and still wants some action as a spectator.

Though, while the addon works as intended, I've encountered a bug!

When a player dies due to very weird reasons (the cars in 67thway, or death by burning) the player will die, but it will continue flying around and it's still marked as alive - though when the player types in chat I can read *DEAD* and his green nickname.

Is there anyway to fix this? I'm only encountering this bug with this addon, so I guess this is the right place to ask.

Thanks for reading, and keep up the good work!

**Comment by MinIsMin** [comment] 2017-06-21 07:54
Do these bugs happen all the time?
I can only reproduce that players are sometimes marked as alive in the scoreboard.

**Comment by djosepaci** [comment] 2017-06-21 11:40
>Do these bugs happen all the time?
Sometimes, when they die.
>I can only reproduce that players are sometimes marked as alive in the scoreboard.
I mean exactly this, and they can't join Spectator Deathmatch for a reason.

**Comment by MinIsMin** [comment] 2017-06-26 14:46
This is **not** an issue with SpecDM since the bug occurs even with no addons installed.
Since it happens without SpecDM and on every map, it seems to be a bug in TTT.

**Closed by MinIsMin** 2017-06-26 14:46 UTC
Labels: bug

**Comment by markusmarkusz** [comment] 2017-06-26 15:27
This is probably a bug with one of your addons.
