### ISSUE TITLE
TTT Damagelogs issue

### ISSUE THREAD

**Issue by mcNuggets1** [Tommy228/TTT_Spectator_Deathmatch#46] opened 2017-01-05 23:56 UTC
newest version lets deaths in specdm appear in damagelogs.

**Comment by markusmarkusz** [comment] 2017-01-06 00:07
whops.
Propably my fault. :p

**Comment by markusmarkusz** [comment] 2017-01-06 01:36
I seem to have confused something. Please describe the problem more precisely. What do you mean by that? If someone dies in the SpecDM then it is logged in the DamageLog, or what?

**Comment by MinIsMin** [comment] 2017-01-06 09:49
Yes, that's because of Damagelog_New function used in sv_specdm_overrides.lua
I don't know why it exists

**Comment by markusmarkusz** [comment] 2017-01-06 10:24
No it isn't because this. It worked before.
The DamageLog_New function is used to filter SpecDM Deaths/Damage Messages.

**Comment by MinIsMin** [comment] 2017-01-06 10:34
@mcNuggets1 Do you mean "<something/world> killed [SpecDMUser]"?

**Comment by mcNuggets1** [comment] 2017-01-06 12:14
That was not the issue.

**Comment by markusmarkusz** [comment] 2017-01-06 12:16
Which message? I can not find any problem with your information.

**Comment by mcNuggets1** [comment] 2017-01-06 12:17
something killed "player name" (role) still appears in the damagelogs after a player in SpecDM killed itself or died some other way.

**Comment by mcNuggets1** [comment] 2017-01-06 12:22
Tested with newest version now, it still is not fixed.
I first thought my modified version of SpecDM would be the problem, but that was not the problem.

**Comment by markusmarkusz** [comment] 2017-01-06 12:31
It can't be something what I've changed.

**Comment by mcNuggets1** [comment] 2017-01-06 12:37
Well, It is caused by the changes made.
Maybe not yours specifically.

**Comment by markusmarkusz** [comment] 2017-01-06 12:40
Have looked once again over it and found nothing that could cause this.

**Comment by MinIsMin** [comment] 2017-01-06 12:43
What damagelogs do you mean? Tommy's? TTT default damagelog? The server damagelog?

**Comment by mcNuggets1** [comment] 2017-01-06 12:50
I use tommys damagelogs.

**Comment by MinIsMin** [comment] 2017-01-06 13:00
On my two servers, there's no message you described.
Even TTT's default ttt_print_damagelog shows nothing:

```
ttt_print_damagelog
	*** Damage log:
	*** Damage log end.
```

Maybe you got an addon, which has a GM:PlayerSilentDeath hook and modifies the damagelog?

**Comment by mcNuggets1** [comment] 2017-01-06 13:01
Funny that, I tested this stuff in my local game without any addons ;)

**Comment by MinIsMin** [comment] 2017-01-06 13:02
Yes, I know you use Tommy's Damagelogs, but it display no message either.

**Comment by mcNuggets1** [comment] 2017-01-06 13:03
That is indeed weird, because I tested it with no addons and plain ttt on a listen server.
When testing with older specdm versions however it works, prior 1.5

**Comment by MinIsMin** [comment] 2017-01-06 13:12
I tested it on a local server with "-noworkshop" and newest SpecDM GitHub version; there's no message.
Feel free to make a screenshot of the damagelog, maybe this helps more.

**Comment by mcNuggets1** [comment] 2017-01-06 13:14
I will do, but I honestly don't think that would help anyone.

**Comment by MinIsMin** [comment] 2017-01-06 13:14
Did you try to use "ttt_print_damagelog"? Is there the message, too?

**Comment by mcNuggets1** [comment] 2017-01-06 13:18
Normal damagelog shows one death.
Tommy's shows two deaths (1 specdm).

https://puu.sh/td4xk/4bdfab305c.png

**Comment by MinIsMin** [comment] 2017-01-06 13:26
I'm using Tommy's last master release and can't reproduce it no matter what I try.
If someone has the same problem, please leave a comment.

**Comment by MinIsMin** [comment] 2017-01-06 13:27
May I add you on Steam to join your local test server? (What's your steam name?)

**Comment by mcNuggets1** [comment] 2017-01-06 13:28
http://steamcommunity.com/id/daviddorn/

**Comment by MinIsMin** [comment] 2017-01-06 13:47
Seems that EntityTakeDamage filters all weapon damage, but no other damage (like falldamage).
Will investigate and create a fix which will come into v1.6 (will be released today).

**Comment by markusmarkusz** [comment] 2017-01-06 13:48
Everything should be filtered.

**Comment by markusmarkusz** [comment] 2017-01-06 15:09
Tested it.
It's really cause by Tommy's DamageLog.
No issue with the spectator deathmatch.

(I used the latest "stable" version from both addons.)

**Comment by MinIsMin** [comment] 2017-01-06 15:10
What do you suggest? Changing the overrides part or TTTDamagelogs?

**Comment by markusmarkusz** [comment] 2017-01-06 15:13
I recommend that you set the brackets correctly. ;)
There are several places in the SpecDM and in the DamageLog where brackets were set incorrectly, which is why bugs occur.

**Comment by MinIsMin** [comment] 2017-01-06 15:38
The issue, as @markusmarkusz said, is in TTTDamagelogs.
Currently, nothing can be done, but TTTDamagelogs will also receive an update in the future.

**Closed** 2017-01-07 13:59 UTC
