### ISSUE TITLE
Console lua error spam.

### ISSUE THREAD

**Issue by thesuperzapper** [Tommy228/TTT_Spectator_Deathmatch#69] opened 2017-11-24 11:07 UTC
### What happened?
Console lua error spam.

### Are there any lua error in the console?
```
[ERROR] addons/ttt_spectator_deathmatch-1.9/lua/cl_spectator_deathmatch.lua:120: Tried to use a NULL entity!
  1. DrawShadow - [C]:-1
   2. fn - addons/ttt_spectator_deathmatch-1.9/lua/cl_spectator_deathmatch.lua:120
    3. unknown - addons/ulib/lua/ulib/shared/hook.lua:109
```

### Are you using a beta branch of GarrysMod? (No, prerelease, dev)
No

### What version of TTT Spectator Deathmatch do you use? (e.g. Workshop, GitHub master, GitHub stable release)
1.9

**Comment by MinIsMin** [comment] 2017-11-24 11:16
Duplicate of #67.
The update wasn't pushed out until now. Should be fixed in https://github.com/Tommy228/TTT_Spectator_Deathmatch/releases/tag/v1.9.3

**Comment by thesuperzapper** [comment] 2017-11-24 11:16
Thanks!

**Closed by MinIsMin** 2017-11-24 11:16 UTC
Labels: duplicate
